# Batch Gradient Descent

Note: I use Linear calculation for activation function
If you want to change the activation function, you can
define it by yourself

## Import Library

In [2]:
import numpy as np
import pandas as pd

In [3]:
def read_file(filename, sep=','):
    '''
    Read the csv files and return it into
    separated value inputs and targets
    '''
    df = pd.read_csv(filename, sep=sep)
    column = list(df.columns)
    inputs = df.loc[:, column[:-1]].to_numpy()
    targets = df.loc[:, column[-1]].to_numpy()
    return inputs, targets

In [4]:
def sigma(inputs, weights):
    '''
    Calculate the dot products between
    inputs and weights each value
    '''
    return np.dot(inputs, weights)

In [15]:
def epoch(inputs, targets, weights, learning_rate, precision=2):
    '''
    Calculate each given value from inputs, targets,
    weights, and learning rate and the result is delta
    weights and its error calculation
    '''
    dw = []
    row = len(inputs)
    col = len(inputs[0])
    outputs = sigma(inputs, weights)
    w_temp = np.zeros(len(inputs[0]))
    err = 0
    for i in range(row):
        temp = []
        for j in range(col):
            if i == 0:
                x =  w_temp[j] + learning_rate * (targets[i] - outputs[i]) * inputs[i][j]
            else:
                x =  dw[i-1][j] + learning_rate * (targets[i] - outputs[i]) * inputs[i][j]
            temp.append(x)

        err = calculate_error(err, targets[i], outputs[i])
        temp.append(err)
        dw.append(temp)
    
    dw = np.array(dw)
    return dw

In [16]:
def calculate_error(err, target, output):
    '''
    Calculate error from the given target and output
    value and initial error
    '''
    result = err + (np.power((target - output), 2) / 2)
    return np.array(result)

In [17]:
def sprint_epoch(inputs, targets, weights, learning_rate, threshold):
    '''
    Calculate each epoch with the given initial inputs, targets, weights,
    learning rate, and threshold
    Return the matrix of shape 3D
    '''
    err = calculate_error(0, targets[0], sigma(inputs, weights)[0])
    res = []
    i = 0
    while err > threshold:
        data = epoch(inputs, targets, weights, learning_rate)
        res.append(data)
        weights = weights + data[-1][:-1]
        err = data[-1][-1]
        i+=1
    
    return res

## Testing

In [19]:
inputs, targets = read_file('models.csv')
weights = np.zeros(len(inputs[0]))
learning_rate = 0.3
threshold = 0.001
se = sprint_epoch(inputs, targets, weights, learning_rate, threshold)
for i in range(len(se)):
    print(se[i])
    print()

[[-0.3  -0.15  0.   -0.3   0.5 ]
 [ 0.   -0.15 -0.3  -0.45  1.  ]
 [ 0.3   0.15 -0.45 -0.75  1.5 ]]

[[-0.19 -0.09  0.   -0.19  0.2 ]
 [-0.23 -0.09  0.04 -0.17  0.2 ]
 [-0.35 -0.22  0.1  -0.04  0.29]]

[[-0.04 -0.02  0.   -0.04  0.01]
 [ 0.06 -0.02 -0.09 -0.08  0.05]
 [ 0.1   0.03 -0.12 -0.13  0.07]]

[[-0.03 -0.02  0.   -0.03  0.01]
 [-0.03 -0.02 -0.01 -0.04  0.01]
 [-0.07 -0.07  0.02  0.01  0.02]]

[[-0.   -0.    0.   -0.    0.  ]
 [ 0.03 -0.   -0.04 -0.02  0.01]
 [ 0.03 -0.   -0.04 -0.02  0.01]]

[[-0.01 -0.    0.   -0.01  0.  ]
 [ 0.01 -0.   -0.01 -0.01  0.  ]
 [-0.02 -0.02 -0.    0.01  0.  ]]

[[-9.51e-04 -4.75e-04  0.00e+00 -9.51e-04  5.02e-06]
 [ 1.70e-02 -4.75e-04 -1.79e-02 -9.92e-03  1.79e-03]
 [ 9.79e-03 -7.68e-03 -1.43e-02 -2.72e-03  2.08e-03]]

[[-1.92e-03 -9.60e-04  0.00e+00 -1.92e-03  2.05e-05]
 [ 8.38e-03 -9.60e-04 -1.03e-02 -7.07e-03  6.10e-04]
 [-2.43e-03 -1.18e-02 -4.89e-03  3.74e-03  1.26e-03]]

[[-5.48e-04 -2.74e-04  0.00e+00 -5.48e-04  1.67e-06]
 [ 9.57e-03 -2.74e-

## Credits
### 13518010 Moh. Mirza Maulana Ikhsan